### ISSUE TITLE
GitHub integration not working (?)

### ISSUE THREAD

**Issue by fernando-playplay** [gitconsensus/GitConsensusService#2]
Hey there! 
First of all, thanks for the tool, it seems very useful!

So I tried installing it on github and doing the configuration for one specific repository. I added the `.gitconsensus.yaml` file at the root folder and created a PR to test it out, got the necessary reactions and... nothing happened (even after the 24 hour delay).

So this is the configuration I use, maybe there's something I didn't set up correctly? I couldn't find any documentation about it, only the [helper tool to create it here](https://www.gitconsensus.com/configBuilder/).

Is there something else I'm missing?
```yaml

# Which version of the consensus rules to use
version: 3

# Add extra labels for the vote counts and age when merging
extra_labels: false

# Don't count any vote from a user who votes for multiple options
prevent_doubles: true

pull_requests:

  # At least two people should sign off on any pull request.
  quorum: 2

  # Required percentage of "yes" votes (ignoring abstentions). It's a good idea to give "no" votes more power.
  threshold: 0.51

  # Number of hours after last action (commit or opening the pull request) before issue can be merged
  merge_delay: 24

  # Number of votes at which the merge_delay gets ignored, assuming no negative votes.
  delay_override: 4

  # Close pull requests that don't pass after seven days without any activity (new commits).
  timeout: 336

  # Do not allow changes to the license.
  license_lock: true

  # Allow the consensus rules (this file) to be changed.
  consensus_lock: false

  # Wait for at least two days before merging any new consensus rules.
  consensus_delay: 48

  # Allow anyone to vote on this project, even if they've never contributed.
  contributors_only: false

  # Don't put any restrictions on who can vote.
  collaborators_only: false
```
